account:
  email:
    max_length: 50
  name:
    max_length: 50
  password:
    min_length: 8
  public:
    max_lenght: 255
  image:
    max_size: 5
  staff:
    per_page: 9
check_box: 1

services:
  per_page: 3
